#!/usr/bin/env ruby

$:.unshift('lib')
require 'hcc'

# command
command = ARGV.shift
unless command and COMMANDS.include? command.to_sym
  usage('not a command')
  exit 1
end

# servers
servers = ARGV.shift
unless servers
  usage('no servers')
  exit 1
end

if servers =~ /(\w)(\d*)\.\.(\w)(\d*)/
  prefix = $1
  server_range = eval(servers.gsub(prefix, ''))
  server_range.each do |s|
  send(command, "#{prefix}#{s}")
else
  send(command, servers)
end
